### ISSUE TITLE
Bug Reports

### ISSUE THREAD

**Issue by Primar13** [Emzi0767/STO-Academy-Build-Tool#3]
Hi Emzi. 

I Broke it! #ItsAllMarcosFault. :)

I'm guessing its probably because I didn't fill in All of the Parts on the Build. Mostly, because its a new build and I havn't decided on all the Parts though. :)

[Original Skill Planner Link] (http://skillplanner.stoacademy.com/2f8c3239e5f114e76ccc361efb3879e5)
[bugreport-4.zip](https://github.com/Emzi0767/STO-Academy-Build-Tool/files/988442/bugreport-4.zip)

**Comment by Emzi0767** [comment]
The tool is abandoned as of December 2016. There are 2 forks that I know of:

* https://github.com/toddashworth/STO-Academy-Build-Tool
* https://github.com/JohnCenaCollective/STO-Academy-Build-Tool

However, I don't know whether they are maintained.
